### ISSUE TITLE
simple ebuild for a clean lxc-gentoo install on a gentoo host

### ISSUE THREAD

**Issue by josch09** [globalcitizen/lxc-gentoo#78]
[lxc-gentoo-99999999.ebuild.txt](https://github.com/globalcitizen/lxc-gentoo/files/71991/lxc-gentoo-99999999.ebuild.txt)

Note: the reason for the .txt-ending is that github does not allow the upload of an ebuild file directly

**Comment by specing** [comment]
cool, but I think we should focus effort into integrating this lxc-gentoo into LXC shipped lxc-gentoo and then continuing development there.

PS: lxc-gentoo does not depend on lxc being present

**Comment by globalcitizen** [comment]
@josch09 Thanks for this. Sorry for the late reply, I have been in China where the connectivity is crap and busy with other things, so it slipped my mind. I have integrated your work in to the main repo, but removed the leading copyright line as this ebuild was not written by the Gentoo Foundation.

@specing The primary reason we don't integrate with LXC proper is licensing. I agree that is a bit of a shame, but that's life. When I started this script a new LXC release wasn't the sort of thing you wanted to wait for, and the kernel/userspace versions were so dynamic and incompatible that it was not really a viable means of development. These days it is more stable, but we still can derive benefit from independent release. For example, I think one of the upcoming changes will be automated cryptographic validation of releases using an automatically updated Gentoo release team key list, possibly using something hacked from last year's https://github.com/gentoo/gentoo-keys tool.

**Comment by specing** [comment]
@globalcitizen What are the license issues? Tbh the in-tree lxc-gentoo is unmaintained, outdated, insecure and as such doing damage to the Gentoo project. How are people supposed to know to use this script and not the in-tree one?

**Comment by globalcitizen** [comment]
@specing From memory I think all of the in-tree ones are a different license to us. If you'd like to go try to get this included somehow, I'm fully in support of your efforts, however I think we may have diverged from the standard behavior of those scripts at this point, so the maintainers may take exception to such a suggestion. I agree with you, it would be a good thing.

**Comment by specing** [comment]
@globalcitizen if you look at the in-tree lxc-gentoo, you'll find that it looks very much like this scrip from a year/two ago.

as for the standard behaviour... I have switched to name/{rootfs/,name.conf,...} scheme for my containers as it works better with ZFS/btrfs subvolumes (mounted at name/).

**Comment by globalcitizen** [comment]
@specing Yes, I use ZFS now too. Anyway, feel free to push to get this included upstream... I suppose they could `git-submodule` it?

**Comment by specing** [comment]
I don't think submoduling is possible, all the templates are in the same dir https://github.com/lxc/lxc/tree/master/templates

**Comment by globalcitizen** [comment]
`ln -s` with a submodule as subdir? ;)

**Comment by specing** [comment]
that could work.

**Comment by globalcitizen** [comment]
Not all packages have a 'build' process separate and prior to the make process, but for those that do, it's possible to just check out the code then move it around and dump the `git` metadata before packaging. Not sure what their process is, I doubt they bother to build in such a manner at present, but as adding a submodule requires this additional process anyway then removing the evidence of such should be trivial.
