### ISSUE TITLE
.gnupg/pubring.gpg doesn't exist

### ISSUE THREAD

**Issue by jcalfee** [globalcitizen/lxc-gentoo#84]
Using: ```bash
PGP_DIR=/root/.gnupg ./lxc-gentoo create -q
```
>I get `Warning: $PGP_DIR is empty or not a directory or /root/.gnupg/pubring.gpg doesn't exist`

The later is true... I have pubring.kbx but not pubring.gpg in that directory.  If I create a symbolic link it works.

**Comment by globalcitizen** [comment]
Sounds like you haven't set up GPG yet.

https://help.github.com/articles/generating-a-new-gpg-key/

**Comment by jcalfee** [comment]
Strange, I followed the directions you might want to make a note about that. I recently setup using the gentoo handbook.. Also validating a signature should not require my key.  Finally a symbolic link caused it to start working ..

**Comment by jcalfee** [comment]
The error is not clear.. I went to an alternative as this was a dead end at the time.
