### ISSUE TITLE
Which lxc is latest?

### ISSUE THREAD

**Issue by krisk0** [globalcitizen/lxc-gentoo#87]
Gentoo, alpine, debian, ubuntu, archlinux and other distros devs might have different opinion on which lxc is currently latest.

My desktop is under Gentoo and server (where I want container to run) is running kinda Debian with lxc 2.0.9. I am not allowed to upgrade software on the server (without proper reason). Had to try different `lxc-gentoo` versions, to make lxc-2.0.9 happy.

I therefore suggest that you state in `README.md` that container created by `lxc-gentoo` is expected to run under lxc version x.y.z . Or better "`lxc-gentoo` version a.b.c creates container for lxc version x0.y0.z0 - x1.y1.z1".

**Comment by globalcitizen** [comment]
Great idea. Actually `lxc-gentoo` is not being actively maintained. If you would like to submit a pull request with your findings that would be appreciated.
